=== Varma-Tushar/CS612_Assignment3_Part_3/DOMParserDTD/Bookstore.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bookstore (book+)>
<!ELEMENT book (title, author, genre)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ATTLIST book id CDATA #REQUIRED>

=== Varma-Tushar/CS612_Assignment3_Part_3/DOMParserDTD/Bookstore-DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "Bookstore.dtd">
<bookstore>
  <book id="1">
	 <title>Gone with the Wind</title>
	 <author>Movie</author>
	 <genre>Classic</genre>
  </book>
  <book id="2">
	 <title>Star Trek</title>
	 <author>TV Series</author>
	 <genre>Science fiction</genre>
  </book>
</bookstore>
